### ISSUE TITLE
Owners

### ISSUE THREAD

**Issue by awgui** [watchdogsrox/splite#10]
how can we get more than one owner to use the "owner only" commands?
I tried:

{
 "ownerId": ["6808104824585561636", "685831186545561636"]
}

but it doesn't work like that... any suggestions on how it might work?

**Comment by 416rehman** [comment]
Solved in 3b3457e9d638db9ac39904052765b57fc94d680d
You can use the new `extraOwnerIds` array field in the config.json for this

**Comment by awgui** [comment]
worked, thx
