### ISSUE TITLE
Unregistering Slash Command

### ISSUE THREAD

**Issue by awgui** [watchdogsrox/splite#11]
Just adding the problem I mentioned on the support server.

if I delete a slash command, it still remains in the bot as registered and working even though the command doesn't exist in the bot files.

**Comment by 416rehman** [comment]
Are you sure you are not using global commands? They take some time to propagate their changes unlike Guild commands (used in spite) which take effect instantly.

**Comment by awgui** [comment]
I'm using the same type of commands as Splite, but I've created new Slash commands with the same settings as Splite's Slash commands. It's been 7 days since I deleted some commands and they still remain in the bot even being deleted.

**Comment by 416rehman** [comment]
Implemented in 833116ccc19840026d32c25882fdd01beb8ac7bb
