### ISSUE TITLE
Does not reliably register slash commands 

### ISSUE THREAD

**Issue by shawnyu5** [watchdogsrox/splite#22]
Upon restarting the application, the slash commands are not always registered

To reproduce, start the bot and add it to a server. Then restart the bot. The slash commands no longer are registered

**Comment by shawnyu5** [comment]
Slash commands only seems to come back after a few restarts

**Comment by 416rehman** [comment]
Fixed in 41ebc9a6888345abc8ae4f4de3b095db15b195a9
