### ISSUE TITLE
confessions is not defined

### ISSUE THREAD

**Issue by shazelrasya** [watchdogsrox/splite#8]
when someone invite the bot to their guilds there's an error in console log, idk what caused this error

ReferenceError: confessions is not defined at utils.js and guildCreate.js

**Comment by 416rehman** [comment]
Fixed in 4c527a7869c823b11856d0a16e7acc421cdf2be8

The issue was being caused because I was still using the old createSlashCommands function to register slash commands manually in utils.js from before the rewrite for discordjs v13.
