### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by SpaceLeft** [watchdogsrox/splite#9]
Please add Music Lavalink with commands button's

**Comment by Itz-Daniel** [comment]
why i have a music implemented but the code is in djsv13 and with good quality

**Comment by SpaceLeft** [comment]
i can take source code bot music?

**Comment by Itz-Daniel** [comment]
Join support server and dm me my name is Danny

**Comment by Itz-Daniel** [comment]
And you will also remember me but it will be a surprise

**Comment by 416rehman** [comment]
Implemented already
